schemaVersion: 2.2.0
components:
  - name: khulnasoft-ui
    attributes:
      gl/inject-editor: true
    container:
      image: registry.gitlab.com/gitlab-org/remote-development/gitlab-remote-development-docs/debian-bullseye-ruby-3.2.patched-golang-1.20-rust-1.65-node-18.16-postgresql-15@sha256:216b9bf0555349f4225cd16ea37d7a627f2dad24b7e85aa68f4d364319832754
      env:
        - name: STORYBOOK_HOST
          value: "0.0.0.0"
      endpoints:
        - name: storybook
          targetPort: 9001
          secure: true
          protocol: http
